#server:
#  port: 8585
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/GestionCliniqueKissi?createDatabaseIfNotExist=true
#    username: diagana_prod
#    password: diagana_prod
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#logging:
#  level:
#    root: WARN
#    com.monnapp: INFO
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
